# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_by_user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sloats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('booked_by_user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('task_from_user', models.CharField(max_length=255)),
                ('task_to_user', models.CharField(max_length=255)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MeetingNotes')),
            ],
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='sloats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sloats'),
        ),
    ]
