# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170729_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sloats',
            name='start_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
