# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170729_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnotes',
            name='status',
            field=models.CharField(default='SCHEDULE', max_length=20),
            preserve_default=False,
        ),
    ]
